### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by john-french** [gmit-sweng-20/ca5-bdd-tdd-cycle2-MatthewSloyan#6]
@MatthewSloyan Very good,  thorough and thought-out tests. One possible improvement could have been to ensure the correct data is supplied to the view [here](https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle2-MatthewSloyan/blob/d429d68a0fc4ba0940fdc18ec9dae018808e64f4/rottenpotatoes/spec/controllers/movies_controller_spec.rb#L40).

Please close this issue to acknowledge receipt of feedback.

**Comment by MatthewSloyan** [comment]
Thanks John for the feedback, I appreciate it!
